name: pygplates
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pygplates
  - cartopy
  - platetectonictools
  - ipykernel # for jupyter
  - pip:
    - PlateTectonicTools
    - gplately